bugfix: correctly error out when ngx.socket.tcp is shutdown before connect
openresty/stream-lua-nginx-module pull request #331
Opened 2023-12-01 09:04 UTC by fffonion

Can be reproduced by following example:
```
user www-data;
daemon off;
master_process off;

events {
}

stream {
	error_log /dev/stdout info;
	server {
		listen 23333;
		    content_by_lua_block {
                        local t = ngx.socket.tcp()
                        t:shutdown("send")
		    }
	}
}
```

This PR moves the check of `u` before calling `ngx_stream_lua_socket_handle_write_error`.

2023-12-12 03:02 UTC, tzssangglass commented
make sense

2023-12-18 14:58 UTC, zhuizhuhaomeng requested changes

2023-12-18 14:58 UTC, zhuizhuhaomeng commented on t/058-tcp-socket.t
> +
extra blank line

2023-12-19 10:15 UTC, fffonion commented on t/058-tcp-socket.t
> +
thanks for the review, addressed.

2023-12-25 00:41 UTC, zhuizhuhaomeng approved these changes

2023-12-25 01:08 UTC, merged

2023-12-25 05:31 UTC, fffonion commented
Thank you!