feature: support lua balancer set proxy bind dynamic
openresty/stream-lua-nginx-module pull request #350
Opened 2024-06-27 01:36 UTC by ytlm

2024-06-27 02:21 UTC, zhuizhuhaomeng approved these changes

2024-06-27 02:23 UTC, zhuizhuhaomeng requested changes

2024-06-27 02:23 UTC, zhuizhuhaomeng commented on src/ngx_stream_lua_balancer.c
> +    const u_char *addr, size_t addr_len, char *err)
```suggestion
int
ngx_stream_lua_ffi_balancer_set_proxy_bind(ngx_stream_lua_request_t *r,
    const u_char *addr, size_t addr_len, char **err)
```

2024-06-27 04:12 UTC, ytlm commented on src/ngx_stream_lua_balancer.c
> +    const u_char *addr, size_t addr_len, char *err)
changed, ths

2024-06-28 00:50 UTC, zhuizhuhaomeng approved these changes

2024-07-01 07:45 UTC, closed without merging

2024-07-01 07:45 UTC, zhuizhuhaomeng commented
I have merged with a small modification.
Please check out the latest code.