bugfix: `setkeepalive` failure on TLSv1.3
openresty/stream-lua-nginx-module pull request #361
Opened 2024-09-06 12:53 UTC by catbro666

porting https://github.com/openresty/lua-nginx-module/pull/2356

When TLSv1.3 is used, the server may send a NewSessionTicket message after the handshake. While this message is ssl-layer data, `tcpsock:sslhandshake` does not consume it.

In the implementation of `setkeepalive`, `recv` is used to confirm the connection is still open and there is no unread data in the buffer. But it treats the NewSessionTicket message as application layer data and then `setkeepalive` fails with this error `connection in dubious state`.

In fact we don't need to peek here, because if the application data is read successfully then the connection is going to be closed anyway. Therefore, `c->recv` can be used instead which will consume the ssl-layer data implicitly.

2024-09-06 15:04 UTC, zhuizhuhaomeng approved these changes

2024-09-06 15:07 UTC, zhuizhuhaomeng requested changes

2024-09-06 15:07 UTC, zhuizhuhaomeng commented on src/ngx_stream_lua_socket_tcp.c
>      int                err;
should remove the err variable.
It is not used now.

2024-09-09 02:48 UTC, catbro666 commented on src/ngx_stream_lua_socket_tcp.c
>      int                err;
done

2024-09-09 23:31 UTC, zhuizhuhaomeng approved these changes

2024-09-09 23:32 UTC, merged